### ISSUE TITLE
Difference between the original?

### ISSUE THREAD

**Issue by rishihahs** [stonier/sophus#10]
What is the difference between this fork and the original strasdat/Sophus? The README seems to indicate that the original is no longer maintained, but a glance at the strasdat repo makes it clear that it is not the case.

When should this repo be used over the original?

**Comment by stonier** [comment]
Ah, I need to update the `README`. Keep this issue here, I'll close it out when I do.

Strasdat was not actively developing any longer so we arranged to fork and release  for both ourselves and the ROS community. He has since resumed active development but this repository is still around to manage releases to ROS distros. It will maintain ABI compatibility, perhaps with the occasional bugfix for a released version over the lifetime of a distro and will sync with upstream between distros to make sure a stable, up to date version is available. There is no active development here that will drift from upstream.

Short story - use this to be compatible with released versions in ROS. If instead you want to dance on the bleeding edge with sources and don't have compatibility issues, use upstream.

**Comment by stonier** [comment]
Updated the README in 28719f43
